version: '3'

services:
#  oracle:
#    container_name: oracle-mvc-dev
#    build:
#      context: ./oracle
#      dockerfile: Dockerfile
#    ports:
#      - 1521:1521

  mariadb:
    container_name: mariadb-mvc-dev
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maria1324!
      MYSQL_DATABASE: mvc
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
